name: Action Install host dependency
description: Install host dependency

# Requires
# vars.PUBLIC_SSH_KEY
# secrets.PRIVATE_SSH_KEY

runs:
  using: "composite"
  steps:
    - name: Install local path
      shell: bash
      run: |
        echo "::add-mask::$HOME"
        local_path=$HOME/.local/bin
        mkdir -p $local_path
        echo "PATH=$local_path:$PATH" >> $GITHUB_ENV
      - name: Install ssh keys
        if: ${{ secrets.PRIVATE_SSH_KEY != '' && vars.PUBLIC_SSH_KEY != '' }}
        shell: bash
        run: |
          cat >id_ed25519.pub <<EOF
          ${{ vars.PUBLIC_SSH_KEY }}
          EOF
          cat >id_ed25519 <<EOF
          ${{ secrets.PRIVATE_SSH_KEY }}
          EOF
          cat >ssh_config <<EOF
          Host github.com
            RequestTTY no
            IdentitiesOnly yes
            IdentityFile $HOME/.ssh/id_ed25519
          EOF
          install -d -m 0700 $HOME/.ssh
          install -D -m 0600 id_ed25519 $HOME/.ssh/id_ed25519
          install -D -m 0644 id_ed25519.pub $HOME/.ssh/id_ed25519.pub
          install -D -m 0644 ssh_config $HOME/.ssh/config
          ssh git@github.com || true
