name: Images Build

# An action to perform a default images build for the selected
# devices. Requires organization secrets vars.PUBLIC_SSH_KEY and
# secrets.PRIVATE_SSH_KEY be defined and valid for successful sync to
# the repositories referenced in the manifest.

# Runs on
# [ self-hosted, linux, almalinux ]

on:
  workflow_dispatch:

env:
  MANIFEST_URI: git@github.com:distro-core/distro-manifest.git
  MANIFEST_BRANCH: main
  MANIFEST_NAME: distro-head-scarthgap.xml

defaults:
  run:
    shell: bash

# concurrency:
#   group: ${{ github.name }}-${{ github.workflow }}-${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  job:
    runs-on: [ self-hosted, linux, almalinux ]
    permissions:
      actions: write
    strategy:
      matrix:
        DISTRO: [ distro-core distro-full ]
        MACHINE: [ sbc-gene-bt06 ]
        IMAGE:  [ distro-image distro-sdk-image ]
    steps:
      - name: Install host dependency
        uses: distro-core/gh-yocto-host-deps@main
      - name: Use repo init and repo sync
        shell: bash
        run: |
          repo init --manifest-url=$MANIFEST_URI --manifest-branch=$MANIFEST_BRANCH --manifest-name=$MANIFEST_NAME --no-clone-bundle --no-repo-verify
          repo sync
      - name: Bitbake fetch
        shell: bash
        run: |
          # $DISTRO $MACHINE $IMAGE
          scripts/images-build --clean-sstate --machine=$MACHINE --distro=$DISTRO --target="-k --runall=fetch $IMAGE"
      # - name: Bitbake build
      #   run: |
      #     # export BB_NO_NETWORK="1"
      #     export BB_NUMBER_THREADS=$(( $(nproc) * 2 / 5 ))
      #     export PARALLEL_MAKE=-j$(( $(nproc) * 2 / 5 ))
      #     for machine in $MACHINES; do
      #       for distro in $DISTROS; do
      #         echo "::group::Bitbake build $machine $distro $IMAGES"
      #         scripts/images-build --machine=$machine --distro=$distro --target="-k $IMAGES"
      #         echo "::endgroup::"
      #       done
      #     done
