name: Images Build

# An action to perform a default images build for the selected
# devices. Requires organization secrets SSH_PUBLIC_KEY and
# SSH_PRIVATE_KEY be defined and valid for successful sync to
# the repositories referenced in the manifest.

# This action is targeted to runners [ self-hosted, almalinux ]

on:
  workflow_dispatch:

env:
  DISTROS: distro-core distro-full
  MACHINES: sbc-gene-bt06
  MANIFEST_URI: git@github.com:distro-core/distro-manifest.git
  MANIFEST_BRANCH: main
  MANIFEST_NAME: distro-head-scarthgap.xml

defaults:
  run:
    shell: bash

jobs:
  job-images-build:
    runs-on: [ self-hosted, almalinux ]
    steps:
      - name: install ssh key
        run: |
          mkdir -p ${HOME}/.ssh
          chmod 0700 ${HOME}/.ssh
          touch ${HOME}/.ssh/id_ed25519.pub
          chmod 0644 ${HOME}/.ssh/id_ed25519.pub
          touch ${HOME}/.ssh/id_ed25519
          chmod 0600 ${HOME}/.ssh/id_ed25519
          touch ${HOME}/.ssh/config
          chmod 0644 ${HOME}/.ssh/config
          cat >${HOME}/.ssh/id_ed25519.pub <<EOF
          ${{ secrets.SSH_PUBLIC_KEY }}
          EOF
          cat >${HOME}/.ssh/id_ed25519 <<EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          if ! grep -q -e '.ssh/id_ed25519$' ${HOME}/.ssh/config; then
            printf '\nHost *\n  IdentitiesOnly yes\n  IdentityFile %s\n\n%s' "${HOME}/.ssh/id_ed25519" "$(cat ${HOME}/.ssh/config)" >${HOME}/.ssh/config
          fi
          ssh git@github.com || true
          mkdir -p ${HOME}/.local/bin
          echo "PATH=${HOME}/.local/bin:$PATH" >> $GITHUB_ENV
          echo "BB_NUMBER_THREADS=$(( $(nproc) * 2 / 5 ))" >> $GITHUB_ENV
          echo "PARALLEL_MAKE=-j$(( $(nproc) * 2 / 5 ))" >> $GITHUB_ENV
      - name: install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ${HOME}/.local/bin/repo
          chmod a+rx ${HOME}/.local/bin/repo
          [ -n "$(command -v repo)" ] || exit 1
      - name: repo init and sync
        shell: bash
        run: |
          repo init --manifest-url=$MANIFEST_URI --manifest-branch=$MANIFEST_BRANCH --manifest-name=$MANIFEST_NAME --no-clone-bundle --no-repo-verify
          repo sync
      - name: scripts/images-build fetch
        run: |
          for distro in $DISTROS; do
            for machine in $MACHINES; do
              scripts/images-build --distro=$distro --machine=$machine --target="--runall=fetch distro-image distro-sdk-image"
            done
          done
      # - name: scripts/images-build build
      #   run: |
      #     scripts/images-build --target="distro-image distro-sdk-image"
