name: sync mirrors
on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '30 5,17 * * *'

jobs:
  sync-mirrors:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: install ssh key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          touch ~/.ssh/id_ed25519.pub
          chmod 0644 ~/.ssh/id_ed25519.pub
          cat >~/.ssh/id_ed25519 <<EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          cat >~/.ssh/id_ed25519.pub <<EOF
          ${{ secrets.SSH_PUBLIC_KEY }}
          EOF
          ssh git@github.com || true
      - name: install repo tool
        shell: bash
        run: |
          PATH="${HOME}/.bin:${PATH}"
          mkdir -p ~/.bin
          echo "path: ${PATH}"
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo
          repo || true
      - name: install host dependency
        shell: bash
        run: |
          source /etc/os-release
          case ${ID} in
          almalinux*)
            echo sudo dnf install -y epel-release
            echo sudo yum install -y dnf-plugins-core
            echo sudo dnf config-manager --set-enabled crb
            echo sudo dnf makecache
            echo sudo dnf upgrade -y
            echo sudo dnf install -y gawk make wget tar bzip2 gzip python3 unzip perl patch \
              diffutils diffstat git cpp gcc gcc-c++ glibc-devel texinfo chrpath \
              ccache socat perl-Data-Dumper perl-Text-ParseWords perl-Thread-Queue \
              python3-pip python3-GitPython python3-jinja2 python3-pexpect xz which \
              rpcgen zstd lz4 cpio glibc-langpack-en libacl git-lfs hostname
            ;;
          debian* | ubuntu* )
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y gawk wget git diffstat unzip texinfo gcc build-essential \
              chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
              iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool \
              file locales libacl1 git-lfs make libxml2-utils
            sudo locale-gen en_US.UTF-8
            ;;
          * )
            exit 1
            ;;
          esac
      - name: checkout self
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: checkout manifest
        uses: actions/checkout@v4
        with:
          repository: distro-core/distro-manifest
          path: layers/distro-manifest
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: repo init/sync
        shell: bash
        run: |
          {
            PATH="${HOME}/.bin:${PATH}"
            repo init -u git@github.com:distro-core/distro-manifest.git -b main -m distro-head-scarthgap.xml -\-no-clone-bundle -\-no-repo-verify
            repo sync
          } >/dev/null 2>&1
      # - name: scripts/images-build
      #   shell: bash
      #   run: |
      #     PATH="${HOME}/.bin:${PATH}"
      #     scripts/images-build --target="--runall=fetch distro-core-image distro-core-sdk-image"
