name: Sync mirrors
on:
  push:
    branches:
      - main
jobs:
  sync-mirrors:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          touch ~/.ssh/id_ed25519.pub
          chmod 0644 ~/.ssh/id_ed25519.pub
          cat >~/.ssh/id_ed25519 <<EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          cat >~/.ssh/id_ed25519.pub <<EOF
          ${{ secrets.SSH_PUBLIC_KEY }}
          EOF
          ssh git@github.com || true
      - uses: actions/checkout@v4
        with:
          repository: distro-core/distro-manifest
          ref: main
          ssh-key: ${{ secrets.SSH_PUBLIC_KEY }}
      - shell: bash
        run: |
          ls -alR
