name: Sync mirrors
on:
  schedule:
    - cron: '30 5,17 * * *'
  push:
    branches-ignore:
      - main
jobs:
  sync-mirrors:
    runs-on: ubuntu-latest
    steps:
      - name: install ssh key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          touch ~/.ssh/id_ed25519.pub
          chmod 0644 ~/.ssh/id_ed25519.pub
          cat >~/.ssh/id_ed25519 <<EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          cat >~/.ssh/id_ed25519.pub <<EOF
          ${{ secrets.SSH_PUBLIC_KEY }}
          EOF
          ssh git@github.com || true
      - name: install repo tool
        shell: bash
        run: |
          mkdir -p ~/.bin
          echo "path: ${PATH}"
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo
          repo || true
      - name: checkout self
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: checkout manifests
        uses: actions/checkout@v4
        with:
          repository: ssh://github.com:distro-core/distro-manifest
          ref: main
          path: layers/distro-manifest
      - shell: bash
        run: |
          ls -alR
