name: Sync mirrors
on:
  push:
    branches:
      - main
jobs:
  sync-mirrors:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          touch ~/.ssh/id_ed25519.pub
          chmod 0644 ~/.ssh/id_ed25519.pub
          cat >~/.ssh/id_ed25519 <<EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          cat >~/.ssh/id_ed25519.pub <<EOF
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKCjMgH4feKUPjyx3ChLwu00bEKsUxAs8Lw7Y3Fm2Riz 142536845+brainhoard-github@users.noreply.github.com
          EOF
          if ssh -i /.ssh/id_ed25519 git@github.com; then
            echo "success"
          else
            echo "failure"
          fi
      - uses: actions/checkout@v4
        with:
          repository: distro-core/distro-manifest
          ref: main
      - shell: bash
        run: |
          ls -alR
