name: Scheduled Update Curated Mirrors

# An action to perform a sync of the curated mirrors utilized
# by distro-core.

# Requires
# secrets.ACTIONS_GITHUB_USER               Valid Personal Account
# secrets.ACTIONS_GITHUB_TOKEN              Valid Personal Token

# runs-on: ubuntu-latest

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '15 1 */2 * *'

jobs:

  job-execute:
    name: ${{ matrix.SRC_URI }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    continue-on-error: true
    env:
      DST_URI: https://${{ secrets.ACTIONS_GITHUB_USER }}:${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/distro-core-curated-mirrors
    strategy:
        max-parallel: 4
        matrix:
          SRC_URI:
            - https://git.openembedded.org/bitbake
            - https://src.libcode.org/pkun/faux.git
            - https://src.libcode.org/pkun/klish.git
            - https://git.yoctoproject.org/meta-amd
            - https://git.yoctoproject.org/meta-arm
            - https://github.com/kraj/meta-clang.git
            - https://git.yoctoproject.org/meta-cloud-services
            - https://git.yoctoproject.org/meta-dpdk
            - https://github.com/Freescale/meta-freescale.git
            - https://github.com/Freescale/meta-freescale-3rdparty.git
            - https://git.yoctoproject.org/meta-intel
            - https://git.yoctoproject.org/meta-lts-mixins
            - https://git.yoctoproject.org/git/meta-mingw
            - https://git.openembedded.org/meta-openembedded
            - https://git.openembedded.org/meta-openembedded-contrib
            - https://github.com/meta-qt5/meta-qt5.git
            - https://code.qt.io/yocto/meta-qt6.git
            - https://github.com/agherzan/meta-raspberrypi.git
            - https://github.com/meta-rust/meta-rust.git
            - https://github.com/Wind-River/meta-secure-core.git
            - https://git.yoctoproject.org/meta-security
            - https://git.yoctoproject.org/meta-selinux
            - https://github.com/STMicroelectronics/meta-st-stm32mp.git
            - https://github.com/linux-sunxi/meta-sunxi.git
            - https://github.com/OE4T/meta-tegra.git
            - https://git.yoctoproject.org/meta-tensorflow
            - https://git.yoctoproject.org/meta-ti
            - https://github.com/uptane/meta-updater.git
            - https://git.yoctoproject.org/meta-virtualization
            - https://github.com/foundriesio/meta-xilinx.git
            - https://github.com/foundriesio/meta-xilinx-tools.git
            - https://git.yoctoproject.org/meta-yocto
            - https://github.com/zehome/MLVPN.git
            - https://git.openembedded.org/openembedded-core
            - https://git.yoctoproject.org/poky
            - https://git.yoctoproject.org/poky-contrib
            - https://github.com/tailscale/tailscale.git
            - https://github.com/veracrypt/VeraCrypt.git
            - https://github.com/veracrypt/VeraCrypt-DCS.git
            - https://github.com/KDE/yocto-meta-kde.git
            - https://github.com/KDE/yocto-meta-kf5.git
            - https://github.com/KDE/yocto-meta-kf6.git
    steps:
      - shell: bash
        run: |
          : set local path
          echo "::add-mask::$HOME"
          if [[ :$PATH: == *:"$HOME/.local/bin":* ]]; then
            echo "PATH alredy contains $HOME/.local/bin"
          else
            localbin=$HOME/.local/bin
            mkdir -p $localbin
            echo "PATH=$localbin:$PATH" >> $GITHUB_ENV
          fi
      - shell: bash
        run: |
          : install git settings
          git config --global http.sslVerify true
          # git config --unset-all http.https://github.com/.extraheader
      - shell: bash
        run: |
          : update SRC_URI to DST_URI
          dst_uri=$DST_URI
          src_uri=${{ matrix.SRC_URI }}
          mirror_basename=$(basename $src_uri .git | tr '[:upper:]' '[:lower:]')
          rm -fr $mirror_basename
          git clone --quiet --mirror $src_uri $mirror_basename
          cd $mirror_basename
          git for-each-ref --format "delete %(refname)" refs/pull | git update-ref --stdin
          git for-each-ref --format "delete %(refname)" refs/meta | git update-ref --stdin
          git for-each-ref --format "delete %(refname)" refs/merge-requests | git update-ref --stdin
          git push --porcelain --mirror $dst_uri/$mirror_basename.git | grep -v "\[up to date\]"
          cd ..
          rm -fr $mirror_basename
