name: Scheduled Workflow Keepalive

# An action to perform enablement on github actions
# workflows. According to github, repository actions
# can be suspended if the repository is inactive for
# 60 days.

# Requires
# liskin/gh-workflow-keepalive@v1.2.1       Github Action

# runs-on: ubuntu-latest

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1 */15 * *'

jobs:
  job-1:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1.2.1
