name: Scheduled Workflow Keepalive

# An action to perform a reset on github actions
# workflows. According to github, repository actions
# can be suspended if the repository is inactive for
# 60 days.

# This action is targeted to runners [ self-hosted, almalinux ]

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0,6,12,18 * * *'

jobs:
  job-workflow-keepalive:
    runs-on:  [ self-hosted, almalinux ]
    permissions:
      actions: write
    steps:
      - name: secrets install ssh key
        run: |
          mkdir -p ${HOME}/.ssh
          chmod 0700 ${HOME}/.ssh
          touch ${HOME}/.ssh/id_ed25519
          chmod 0600 ${HOME}/.ssh/id_ed25519
          touch ${HOME}/.ssh/id_ed25519.pub
          chmod 0644 ${HOME}/.ssh/id_ed25519.pub
          touch ${HOME}/.ssh/config
          chmod 0644 ${HOME}/.ssh/config
          cat >${HOME}/.ssh/id_ed25519 <<EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          cat >${HOME}/.ssh/id_ed25519.pub <<EOF
          ${{ secrets.SSH_PUBLIC_KEY }}
          EOF
          if ! grep -q -e '.ssh/id_ed25519$' ${HOME}/.ssh/config; then
            printf '\nHost *\n  IdentitiesOnly yes\n  IdentityFile %s\n\n%s' "${HOME}/.ssh/id_ed25519" "$(cat ${HOME}/.ssh/config)" >${HOME}/.ssh/config
          fi
          ssh git@github.com || true
      - uses: distro-core/gh-workflow-keepalive@v1
      - name: checkout self
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: commit timestamp
        shell: bash
        run: |
          timestamp=$(date -Isec)
          branch=timestamp-${timestamp//:/-}
          git checkout -b $branch
          echo $timestamp >.timestamp
          git add .timestamp
          git commit -m "Update $timestamp"
          git push -u origin $branch
