name: Workflow Keepalive

# Utilize an action to perform a reset on github actions
# workflows. According to github, repository actions
# can be suspended if the repository is inactive for
# 60 days.

on:
  schedule:
    - cron: '0 * * * *'

jobs:

  job-workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: self-hosted
    permissions:
      actions: write
    steps:
      - uses: distro-core/gh-workflow-keepalive@v1
      # - name: checkout self
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ github.repository }}
      #     ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - name: commit timestamp
      #   shell: bash
      #   run: |
      #     timestamp=$(date -Isec)
      #     git checkout -b  ${timestamp//:/-}
      #     echo $timestamp >.timestamp
      #     git add .timestamp
      #     git commit -m "Update $timestamp"
      #     git push -u origin  ${timestamp//:/-}
